# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25ba475f26f97f9b65178dc7593423b1dd84afc7e05ae34f687a8be60c2b4c70fb4c50c269bbfd76a5ec367339b733218dc3d46e8f361849d6ddfa5110528243

test:
  secret_key_base: bbf6122a14b508761cd9ed3eff0172cf8128d085ded4d50913426060dcafa369877ac90ce3ea86e6c6eb0b8467801aca46dd07d4757bf2bf3966127e5a7b12c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
